---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sys-admin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sys-admin-role
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - ""
  - apps
  - batch
  - extensions
  - admissionregistration.k8s.io
  - apiextensions.k8s.io
  - apiregistration.k8s.io
  - authentication.k8s.io
  - authorization.k8s.io
  - certificates.k8s.io
  - coordination.k8s.io
  - events.k8s.io
  - networking.k8s.io
  - rbac.authorization.k8s.io
  - scheduling.k8s.io
  - storage.k8s.io
  resources:
  - '*'
  verbs:
  - '*' # ["get", "list", "watch", "create", "update", "patch", "delete"]
- nonResourceURLs:
  - '*' #'*' in a nonResourceURL is a suffix glob match
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sys-admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sys-admin-role
subjects:
- kind: ServiceAccount
  name: sys-admin
  namespace: kube-system
