---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-stage-gameconfig
data:
  game-config-service.properties: |
    server.port=8098

    spring.jpa.hibernate.ddl-auto=none
    spring.datasource.url=jdbc:mysql://db_domain:3306/database
    spring.datasource.username=user
    spring.datasource.password=password

    spring.hazelcast.config=hazelcast-client.xml

    logging.level.root=INFO
    logging.level.com.game=DEBUG
    logging.file=/logs/gameconfig_stage.log
    logging.pattern.console=%d{HH:mm:ss.SSS} | GAME-SESSION | %-5level | %msg%n
    logging.pattern.file=%d{HH:mm:ss.SSS} | GAME-SESSION | %-5level | %msg%n
