---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-elasticsearch-master-2-pv
  namespace: logging
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/usr/share/elasticsearch/data/nodes"
