---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gameconfig-stage-pv
  labels:
    type: local
spec:
  storageClassName: gameconfig-stage-pv
  capacity:
    storage: 1024Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/sys/gameconfig/"
